- hosts: jenkins
  remote_user: vagrant
  serial: 1
  sudo: yes
  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

- hosts: jenkins
  remote_user: vagrant
  serial: 1
  sudo: yes
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk

- hosts: jenkins
  remote_user: vagrant
  serial: 1
  sudo: yes
  roles:
    - geerlingguy.jenkins