- hosts: jenkins
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

- hosts: jenkins
  remote_user: vagrant
  sudo: yes
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk

- hosts: jenkins
  remote_user: vagrant
  sudo: yes
  vars:
    jenkins_plugins:
      - git
      - sonar
      - ssh
      - docker-build-publish
  roles:
    - geerlingguy.jenkins

- name: Install Docker
  remote_user: vagrant
  sudo: yes
  hosts: jenkins
  roles:
    - angstwad.docker_ubuntu